l_braz_por:
 DIVISION_QUEUED: "$N$ Unidade"
 DIVISIONS_QUEUED: "$N$ Unidades"
 ARMY_LEDGER_ARMIES: "Unidades"
 ARMY_LEDGER_THRESHOLD_EQUIPMENT_RATIO: "Proporção de equipamentos atendidos para unidades em campo"
 ARMY_LEDGER_THRESHOLD_BASIC_TEMPLATE_INFO: "Lista de modelos de unidade"
 ARMY_LEDGER_THRESHOLD_FUZZY_TEMPLATE_COUNT: "Contagens aproximadas de unidades por modelo"
 ARMY_LEDGER_THRESHOLD_TEMPLATE_COUNT: "Contagens de unidades por modelo"
 TRIGGER_DIVISIONS_MORE_THAN: "Possui mais do que $AMOUNT|H$ unidades"
 TRIGGER_DIVISIONS_LESS_THAN: "Possui no mínimo $AMOUNT|H$ unidades"
 TRIGGER_DIVISIONS: "Unidades"
 DIVISIONS: "Unidades"
 DIVISIONS_COUNTRY: "§T$COUNTRY|H$ tem $VAL|H$ Unidades§!"
 ARMY_TAB: "Unidades"
 TOPBAR_ARMY_DESC: "Veja uma visão geral de suas unidades."
 COMBAT_COMMITED_LABEL: "$COUNT$ Unidades"
 ARMY_ARMY_LABEL: "Visão geral da unidade"
 ARMY_DIVISONS_TAB: "§YUnidades§!"
 ARMY_DIVISIONS_ACTIVE: "$N$ Unidades de Combate"
 ARMY_DIVISIONS_BUTTON: "§GClique§! para selecionar.\n§GClique§! mantendo §HShift pressionado§! para selecionar vários unidades.\n§GClique com o botão direito§! para ver o unidades."
 EXP_MULTIPLE_DIVISIONS: "$COUNT$/$TOTAL$ Unidades"
 EXP_SINGLE_DIVISION: "1 Unidade"
 VOL_MULTIPLE_DIVISIONS: "$COUNT$ Unidades"
 VOL_SINGLE_DIVISION: "1 Unidade"
 LEDGER_DIVISIONS: "Unidades"
 REQUEST_EXPEDITIONARIES_DIVISIONS_COUNT: "$NUM_DIVS|Y$ Total de unidades"
 UNITS_VIEW_DIVISIONS_COUNT: "$DIV|G$ Unidades"
 group_militia_title: "Militia Companies"
 group_airborne_infantry_title: "Airborne Companies"
 group_airmobile_title: "Airmobile Companies"
 group_special_forces_title: "Ranger/Special Operations Companies"
 group_marine_infantry_title: "Marine Companies"
 group_infantry_title: "Infantry Companies"
 group_mobile_title: "Motorized Companies"
 group_armor_title: "Mechanized/Armored Companies"
 group_combat_support_title: "Combat Support Companies"